name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CI: true

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.2
        with:
          bun-version: 1.2.23

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Type check
        run: bun run typecheck

      - name: Lint (Biome)
        run: bun run lint . --reporter github

      - name: Biome checks
        run: bun run check . --reporter github

      - name: Run tests
        run: bun run test
